blank_issues_enabled: false
contact_links:
  - name: Home Assistant Community
    url: https://community.home-assistant.io/t/harvia-sauna-remote-control/397324
    about: Ask questions and share your setup in the HA Community thread
